name: TRACE CI Workflow

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  backend-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install backend dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest gunicorn uvicorn[standard] -r requirements.txt

      - name: Lint backend code with Flake8
        run: flake8 backend/

      - name: Run backend tests
        # Assuming you have a 'tests' directory in your backend, e.g., 'backend/tests/'
        # If no tests exist yet, this step will be conceptual or can be skipped.
        run: |
          echo "No backend tests found. Skipping test execution."
          # If you had tests, you would run: pytest backend/tests/
        continue-on-error: true # Allow CI to pass even if tests are not yet implemented

  frontend-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install frontend dependencies
        run: npm ci
        working-directory: frontend

      - name: Lint frontend code with ESLint
        run: npm run lint
        working-directory: frontend

      - name: Build frontend application
        run: npm run build
        working-directory: frontend

      - name: Run frontend tests
        # Assuming you have tests configured in your package.json, e.g., "test": "jest"
        # If no tests exist yet, this step will be conceptual or can be skipped.
        run: |
          echo "No frontend tests found. Skipping test execution."
          # If you had tests, you would run: npm test
        continue-on-error: true # Allow CI to pass even if tests are not yet implemented